### ISSUE TITLE
Rimozione modalità ingresso IT

### ISSUE THREAD

**Issue by astagi** [hrzucchetti/zconnect-verificaC19-sdk-ios#4]
## Feature description

Rimuovere e adeguarsi all'ultima versione del SDK ufficiale rimuovendo la modalità di ingresso IT. [CHANGELOG](https://github.com/ministero-salute/it-dgc-verificac19-sdk-onboarding/blob/main/CHANGELOG.md#1110---13062022)

**Comment by salmattia** [comment]
Implementato con release [1.1.12](https://github.com/hrzucchetti/zconnect-verificaC19-sdk-ios/releases/tag/1.1.12)
